### ISSUE TITLE
Module did not self-register problem

### ISSUE THREAD

**Issue by tastypear** [rastapasta/pokemon-go-mitm-node#10]
tried to ```rm -r node_modules``` and ```npm install``` but doesn't wrok
```bash
root@localhost:~/pokemon-go-mitm-node# coffee example.logTraffic.coffee
Error: Module did not self-register.
  at Error (native)
  at Object.Module._extensions..node (module.js:568:18)
  at Module.load (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:417:12)
  at Function.Module._load (module.js:409:3)
  at Module.require (module.js:468:17)
  at require (internal/module.js:20:19)
  at bindings (/root/pokemon-go-mitm-node/node_modules/pokemongo-protobuf/node_modules/node-protobuf/node_modules/bindings/bindings.js:76:44)
  at Object.<anonymous> (/root/pokemon-go-mitm-node/node_modules/pokemongo-protobuf/node_modules/node-protobuf/protobuf.js:9:35)
  at Module._compile (module.js:541:32)
  at Object.Module._extensions..js (module.js:550:10)
  at Module.load (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:417:12)
  at Function.Module._load (module.js:409:3)
  at Module.require (module.js:468:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/root/pokemon-go-mitm-node/node_modules/pokemongo-protobuf/index.js:2:16)
  at Module._compile (module.js:541:32)
  at Object.Module._extensions..js (module.js:550:10)
  at Module.load (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:417:12)
  at Function.Module._load (module.js:409:3)
  at Module.require (module.js:468:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/root/pokemon-go-mitm-node/lib/pokemon-go-mitm.coffee:7:14)
  at Object.<anonymous> (/root/pokemon-go-mitm-node/lib/pokemon-go-mitm.coffee:1:1)
  at Module._compile (module.js:541:32)
  at Object.loadFile (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:417:12)
  at Function.Module._load (module.js:409:3)
  at Module.require (module.js:468:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/root/pokemon-go-mitm-node/example.logTraffic.coffee:9:17)
  at Object.<anonymous> (/root/pokemon-go-mitm-node/example.logTraffic.coffee:1:1)
  at Module._compile (module.js:541:32)
  at Object.exports.run (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/coffee-script.js:134:23)
  at compileScript (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:224:29)
  at compilePath (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:174:14)
  at Object.exports.run (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:98:20)
  at Object.<anonymous> (/usr/local/lib/node_modules/coffee-script/bin/coffee:7:41)
  at Module._compile (module.js:541:32)
  at Object.Module._extensions..js (module.js:550:10)
  at Module.load (module.js:458:32)
  at tryModuleLoad (module.js:417:12)
  at Function.Module._load (module.js:409:3)
  at Module.runMain (module.js:575:10)
  at run (node.js:348:7)
  at startup (node.js:140:9)
  at node.js:463:3

**Comment by ksemeks** [comment]
Update Node [source](https://github.com/rastapasta/pokemon-go-mitm-node/issues/8)

**Comment by rastapasta** [comment]
thanks @ksemeks :)
