### ISSUE TITLE
protobuf parse failed

### ISSUE THREAD

**Issue by AVVS** [rastapasta/pokemon-go-mitm-node#11]
<details>
```
/Users/vitaly/projects/pokemon-go-mitm-node/node_modules/node-protobuf/protobuf.js:53
    var result = native.parse(buffer, schema, limit, warn);
                        ^

Error: Malformed protocol buffer
  at Error (native)
  at pb_wrapper.parse (/Users/vitaly/projects/pokemon-go-mitm-node/node_modules/node-protobuf/protobuf.js:53:25)
  at /Users/vitaly/projects/pokemon-go-mitm-node/lib/pokemon-go-mitm.coffee:52:25
  at /Users/vitaly/projects/pokemon-go-mitm-node/node_modules/http-mitm-proxy/lib/proxy.js:966:12
  at /Users/vitaly/projects/pokemon-go-mitm-node/node_modules/async/lib/async.js:181:20
  at Object.async.forEachOf.async.eachOf (/Users/vitaly/projects/pokemon-go-mitm-node/node_modules/async/lib/async.js:233:13)
  at Object.async.forEach.async.each (/Users/vitaly/projects/pokemon-go-mitm-node/node_modules/async/lib/async.js:209:22)
  at Proxy._onRequestEnd (/Users/vitaly/projects/pokemon-go-mitm-node/node_modules/http-mitm-proxy/lib/proxy.js:965:9)
  at end (/Users/vitaly/projects/pokeVitalys-MacBook-Pro:pokemon-go-mitm-node vitaly$ 
```
<summary>Fails to parse ~~response~~ request!:
   -----------------------
</summary>
</details>

**Comment by AVVS** [comment]
Actually that was a request

**Comment by rastapasta** [comment]
Could you start the server with the debug: true option to see which request it is about?
Are you using (lib)protobuf >= 3?

**Comment by AVVS** [comment]
@rastapasta protobuf 3.0.0-beta-3. Also it doesn't happen all the time either. I've added try/catch to see what could be the case on line 52

```coffee
      try
        data = POGOProtos.parse buffer, @requestEnvelope
      catch e
        @log "[---] Failed to parse request buffer of #{ctx.clientToProxyRequest.url}"
        return callback e
```

So we'll see what it is if it happens again, and I'll try debug version too

**Comment by AVVS** [comment]
Hex of the buffer that did not parse

```
[+++] Request to /plfe/268/rpc
[---] Failed to parse request buffer of /plfe/268/rpc, a0722016000000f05b3d2016000000c02d00c1010a99018080808084a4f5a841808080808ca4f5a8418080808094a4f5a841808080809ca4f5a84180808080a4a4f5a84180808080aca4f5a84180808080b4a4f5a84180808080bca4f5a84180808080c4a4f5a84180808080cca4f5a84180808080d4a4f5a84180808080dca4f5a84180808080e4a4f5a84180808080eca4f5a84180808080f4a4f5a84180808080b4a7f5a84180808080cca7f5a841121100000000000000000000000000000000001900000020b9244c402100000040c30546402202087e220b08041207088ea194cfe02a2203088101222e0805122a0a283035646166353136333563383236313164316161633935633062303531643365633038386139333032a802080612a3020aa002b3ff7c475308ab259e6d913f7930fa75bc409ceb2fad158e32a1a604809e9bfc2adda0cf3f7ad2abb75e7a77873e913d6e148919ab18dcf3d2ced2f011dce33f2eb9aac5877d9a770f0af8170f4f4cadeea9fabe202957dfcf369c0a393b28ed1c4af738f01424290ee9d9e4b9c5ed5d4e9da97d1d0437ba44e79564b95cdd0b316fd93679437c982d35b32a58402f9b50bed5b5b0c558037ac24a6acbba623429c0bc774907c82a3d5d364e9e5354126c47c2d3d2fcbfb405acddb0091d0
```

**Comment by AVVS** [comment]
weird, wrong number of octets printed

**Comment by AVVS** [comment]
That same buffer in base64:

```
echo "qZk7FgAAAGAAmjsWAAAAwC0AwQEKmQGAgICAhKT1qEGAgICAjKT1qEGAgICAlKT1qEGAgICAnKT1qEGAgICApKT1qEGAgICArKT1qEGAgICAtKT1qEGAgICAvKT1qEGAgICAxKT1qEGAgICAzKT1qEGAgICA1KT1qEGAgICA3KT1qEGAgICA5KT1qEGAgICA7KT1qEGAgICA9KT1qEGAgICAtKf1qEGAgICAzKf1qEESEQAAAAAAAAAAAAAAAAAAAAAAGQAAAEC4JExAIQAAAADFBUZAIgIIfiILCAQSBwiOoZTP4CoiAwiBASIuCAUSKgooMDVkYWY1MTYzNWM4MjYxMWQxYWFjOTVjMGIwNTFkM2VjMDg4YTkzMDKoAggGEqMCCqAClR+cgsIhuyOj2erniTvN5k549d24gOsEfxO9sCV5DoPPb1Nwi4wXsMsO7QVjTulsaxFuyO9OeMabLcTgJ7XWab+qrWlkBIk4rmQQtEnbQL45HsAZq2H/AOSwFGjqihyGL+qerznIO/B6wzd1mUmA7amK0DerysIQaYP6oZ4Pilchz02NWO+zfKc8v+6FDNjzRpkhcqsrVSfLZ7TgS78UAPp+yelFq795RnAtyXBxWauv4+k9sAJD6zVDUhLoZk5ucGIdPJFIUS65Hz4HtFqStmisZ3deQ5/hDvE4JG2G6exN2m12o2AbEEMU3E8Si70p38rG9DvIafDJ5kBAN1f/JFruuFtsKU1hwyK3ZPrMnC3VuL/jTihGz/sBkmbgf4SEOQAAAEC4JExAQQAAAADFBUZASQAAAAAAACRAWlsKQBZOk9N/ivTQX/hdbpNbndBfUYfusDNbV+QFTdPrWKC7y+eAVER+XqlX5AFKWDkN4ZMT60ji+qspe5fz3U7fx30Qm9OF0OAqGhBSsc7f57VR4UwoUemoWB/fYOsO" | base64 -D - | protoc --decode_raw
Failed to parse input.
```

**Comment by AVVS** [comment]
Could it be that protos should be updated? I've seen a lot of commits for the past 3 days in https://github.com/AeonLucid/POGOProtos

**Comment by rastapasta** [comment]
was updated 14 hours ago, corresponding branch is https://github.com/rastapasta/node-pokemongo-protobuf and will be updated in a sec. just wondering, have it running on multiple instances with a lot of test traffic and don't get it. can u reproduce with a specific in-game action or is it on every request? cheers!

**Comment by AVVS** [comment]
@rastapasta since I sit at home my only "game action" is having the game launched. This can be reproduced in the following sequence:

1. kill the app
2. start mitm proxy (traffic logger for instance)
3. launch the app - everything is nice and dandy
4. stop mitm proxy
5. wait some time
6. start mitm proxy
7. lots of requests will start going through (afaik they are batched or smth)
8. crash

**Comment by AVVS** [comment]
@rastapasta any luck here?

**Comment by AVVS** [comment]
I'm testing more, this could be related to node version or server issues, not sure though. Will let you know if I have more on it

**Comment by rastapasta** [comment]
Also the upcoming version will have better catching of the parse errors - so even if one decrypt might fail, the software keeps running

**Comment by AVVS** [comment]
Ok, closing since thats going to be handled 👍

**Comment by R1NZLR** [comment]
I got it figured out. Thanks! Hoxy is much more forgiving
