### ISSUE TITLE
Error with creating certificate

### ISSUE THREAD

**Issue by waterblast74** [rastapasta/pokemon-go-mitm-node#123]
ok so i cannot seem to run the example.logTraffic.coffee in a terminal with the command "coffee example.logTraffic.coffee". So i just launched the file instead from the folder and got the following in the terminal with the executed code

"
Last login: Fri Aug  5 12:11:40 on ttys000
Apples-MBP-5:~ apple$ /Users/apple/Downloads/pokemon-go-mitm-node-master/example.logTraffic.coffee ; exit;
/Users/apple/Downloads/pokemon-go-mitm-node-master/example.logTraffic.coffee: line 2: syntax error near unexpected token `('
/Users/apple/Downloads/pokemon-go-mitm-node-master/example.logTraffic.coffee: line 2: `  Pokemon Go(c) MITM node proxy'
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
"
And I can't see any certificate in the folder, i tried showing hidden folders as well but to no avail. What is the issue? I'm running on a Macbook Pro if that is relevant

**Comment by waterblast74** [comment]
alright so i used the cd command, the line says

"Apples-MBP-5:~ apple$ cd /Users/apple/Downloads/pokemon-go-mitm-node-master".

Then i tried running coffee example.logTraffic.coffee and the following was returned

"Error: Cannot find module 'http-mitm-proxy'
  at Function.Module._resolveFilename (module.js:325:15)
  at Function.Module._load (module.js:276:25)
  at Module.require (module.js:353:17)
  at require (internal/module.js:12:17)
  at Object.<anonymous> (/Users/apple/Downloads/pokemon-go-mitm-node-master/lib/pokemon-go-mitm.coffee:6:9)
  at Object.<anonymous> (/Users/apple/Downloads/pokemon-go-mitm-node-master/lib/pokemon-go-mitm.coffee:1:1)
  at Module._compile (module.js:409:26)
  at Object.loadFile (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:300:12)
  at Module.require (module.js:353:17)
  at require (internal/module.js:12:17)
  at Object.<anonymous> (/Users/apple/Downloads/pokemon-go-mitm-node-master/example.logTraffic.coffee:9:17)
  at Object.<anonymous> (/Users/apple/Downloads/pokemon-go-mitm-node-master/example.logTraffic.coffee:1:1)
  at Module._compile (module.js:409:26)
  at Object.exports.run (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/coffee-script.js:134:23)
  at compileScript (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:224:29)
  at compilePath (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:174:14)
  at Object.exports.run (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:98:20)
  at Object.<anonymous> (/usr/local/lib/node_modules/coffee-script/bin/coffee:7:41)
  at Module._compile (module.js:409:26)
  at Object.Module._extensions..js (module.js:416:10)
  at Module.load (module.js:343:32)
  at Function.Module._load (module.js:300:12)
  at Function.Module.runMain (module.js:441:10)
  at startup (node.js:139:18)
  at node.js:968:3
"
Still no certificate :)

**Comment by jmoriau** [comment]
sigh, did you even read the whole README ?
Do you have the latest node ? Did you `npm install` ?
Also issues are not a support forums, they are mostly for reporting "an issue" with the project, failing to read the README or to correctly install a few dependencies does not qualify. Try googling first.
