### ISSUE TITLE
Hoxy not handling client socket disruption

### ISSUE THREAD

**Issue by AVVS** [rastapasta/pokemon-go-mitm-node#20]
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: socket hang up
  at createHangUpError (_http_client.js:250:15)
  at Socket.socketOnEnd (_http_client.js:342:23)
  at emitNone (events.js:91:20)
  at Socket.emit (events.js:185:7)
  at endReadableNT (_stream_readable.js:926:12)
  at _combinedTickCallback (internal/process/next_tick.js:74:11)
  at process._tickCallback (internal/process/next_tick.js:98:9)
```

To reproduce: launch hoxy, add proxy to phone, launch app, hit power button on the phone -> socket abruptly closed -> crash

I've checked hoxy repo and it has a similar issue opened. Wonder if we'd have to monkey-patch or are able to get access to socket in some normal way

**Comment by rastapasta** [comment]
thanks for looking into it! will have to postpone hoxy for now, the uncaught socket hang up and (most likely) ssl handshake issues are blocking for now, will talk to waryas, he continued to improve the usage of http-mitm-proxy - cheers!

**Comment by R1NZLR** [comment]
Im gonna try mitm again. But hoxy is all thats worked for me so far. Keep up the good work!
