### ISSUE TITLE
inject request broken?

### ISSUE THREAD

**Issue by prajwalkman** [rastapasta/pokemon-go-mitm-node#31]
I'm unable to get the autorelease example working. Not getting any error, but not receiving a response either. In fact I don't think a request is even being sent.

**Comment by dotaxis** [comment]
I experimented with this and found that it is indeed broken.

In lib/pokemon-go-mitm.coffee:

`for request in @requestInjectQueue`
`unless data.requests.length < 5`
`@log "[-] Delaying inject of #{request.action} because RequestEnvelope is full"`
`break`

There is no function to actually "go back" and retry the injection.

I found that changing it to show

`unless data.requests.length < 10`

makes the injection work, but the game crashed on the loading screen when I had duplicate Pokemon (likely because of an untimely injection). I also feel like this is a poor workaround.

I'm working on rewriting this part and will post a fix here later (or maybe do a pull request, I'm not a dev so I don't know).

**Comment by rastapasta** [comment]
hey hey! thanks for catching! indeed the requestsInjectQueue is being reset even though no inject happens. it needs to be queued, as a requestEnvelope allows max 5 included requests.

if you want to trigger a seperate instant API request, you can just replace it with

`server.craftRequest "ReleasePokemon", pokemon_id: releaseId, (result) -> console.log result`

which will work without having to wait for the next injection possibility 😄 

Cheers!

**Comment by dotaxis** [comment]
Hey, I tried running it like that but with setTimeout so the game doesn't crash after catching a Pokemon, but I'm not getting any console output from it. The request IS being crafted and working, just no log. Any suggestions?

> 			#wait 30 seconds before releasing pokemon
			releasePokemon = ->
				server.craftRequest "ReleasePokemon", pokemon_id: releaseId, (data) -> 
					if data.result is "SUCCESS"
						console.log "[+] Released #{pokemon.pokemon_id}!"
					else
						console.log "[-] Failed to release #{pokemon.pokemon_id}"
			setTimeout releasePokemon, 30000

**Comment by rastapasta** [comment]
Oh, sorry, my fault, the change to use promises for server.craftRequest was already merged - so correct usage is:
>				server
					.craftRequest "ReleasePokemon", pokemon_id: releaseId
					.then (data) -> 
						if data.result is "SUCCESS"
						....

**Comment by dotaxis** [comment]
That worked a bit better. I kept getting negative output so I ran data through json.stringify and found that it should be:

> .then (data) ->
    if data.success
    ...

Thank you kindly for your help!

**Comment by prajwalkman** [comment]
I got it working! Thanks a lot! Feel free to use it as an example if you wish!

https://gist.github.com/prajwalkman/d7e17e90f0fc5ede42c56f0307da0182

**Comment by justinleewells** [comment]
I can't seem to inject at all. Any idea what I'm doing wrong? (All pokemon data is in a data field on the pokemon, so I'm accessing the right id)

```
function transfer(arr) {
  if (arr.length > 0) {
    var p = arr.pop();
    setTimeout(function () {
      console.log('TRANSFER: ' + p.data.cp + ' CP ' + p.data.pokemon_id);
      server.craftRequest("ReleasePokemon", {
        pokemon_id: p.data.id
      }).then(function () {
        console.log(data);
      });
      inventory.release(p.data.id);
      transfer(arr);
    }, 750);
  }
}
```

It never logs `@log "[+] Crafting request for #{action}"` and I am getting this error:

```
Unhandled rejection StatusCodeError: 502 - {"type":"Buffer","data":[60,33,68,79,67,84,89,80,69,32,104,116,109,108,62,10,60,104,116,109,108,32,108,97,110,103,61,101,110,62,10,32,32,60,109,101,116,97,32,99,104,97,114,115,101,116,61,117,116,102,45,56,62,10,32,32,60,109,101,116,97,32,110,97,109,101,61,118,105,101,119,112,111,114,116,32,99,111,110,116,101,110,116,61,34,105,110,105,116,105,97,108,45,115,99,97,108,101,61,49,44,32,109,105,110,105,109,117,109,45,115,99,97,108,101,61,49,44,32,119,105,100,116,104,61,100,101,118,105,99,101,45,119,105,100,116,104,34,62,10,32,32,60,116,105,116,108,101,62,69,114,114,111,114,32,53,48,50,32,40,83,101,114,118,101,114,32,69,114,114,111,114,41,33,33,49,60,47,116,105,116,108,101,62,10,32,32,60,115,116,121,108,101,62,10,32,32,32,32,42,123,109,97,114,103,105,110,58,48,59,112,97,100,100,105,110,103,58,48,125,104,116,109,108,44,99,111,100,101,123,102,111,110,116,58,49,53,112,120,47,50,50,112,120,32,97,114,105,97,108,44,115,97,110,115,45,115,101,114,105,102,125,104,116,109,108,123,98,97,99,107,103,114,111,117,110,100,58,35,102,102,102,59,99,111,108,111,114,58,35,50,50,50,59,112,97,100,100,105,110,103,58,49,53,112,120,125,98,111,100,121,123,109,97,114,103,105,110,58,55,37,32,97,117,116,111,32,48,59,109,97,120,45,119,105,100,116,104,58,51,57,48,112,120,59,109,105,110,45,104,101,105,103,104,116,58,49,56,48,112,120,59,112,97,100,100,105,110,103,58,51,48,112,120,32,48,32,49,53,112,120,125,42,32,62,32,98,111,100,121,123,98,97,99,107,103,114,111,117,110,100,58,117,114,108,40,47,47,119,119,119,46,103,111,111,103,108,101,46,99,111,109,47,105,109,97,103,101,115,47,101,114,114,111,114,115,47,114,111,98,111,116,46,112,110,103,41,32,49,48,48,37,32,53,112,120,32,110,111,45,114,101,112,101,97,116,59,112,97,100,100,105,110,103,45,114,105,103,104,116,58,50,48,53,112,120,125,112,123,109,97,114,103,105,110,58,49,49,112,120,32,48,32,50,50,112,120,59,111,118,101,114,102,108,111,119,58,104,105,100,100,101,110,125,105,110,115,123,99,111,108,111,114,58,35,55,55,55,59,116,101,120,116,45,100,101,99,111,114,97,116,105,111,110,58,110,111,110,101,125,97,32,105,109,103,123,98,111,114,100,101,114,58,48,125,64,109,101,100,105,97,32,115,99,114,101,101,110,32,97,110,100,32,40,109,97,120,45,119,105,100,116,104,58,55,55,50,112,120,41,123,98,111,100,121,123,98,97,99,107,103,114,111,117,110,100,58,110,111,110,101,59,109,97,114,103,105,110,45,116,111,112,58,48,59,109,97,120,45,119,105,100,116,104,58,110,111,110,101,59,112,97,100,100,105,110,103,45,114,105,103,104,116,58,48,125,125,35,108,111,103,111,123,98,97,99,107,103,114,111,117,110,100,58,117,114,108,40,47,47,119,119,119,46,103,111,111,103,108,101,46,99,111,109,47,105,109,97,103,101,115,47,98,114,97,110,100,105,110,103,47,103,111,111,103,108,101,108,111,103,111,47,49,120,47,103,111,111,103,108,101,108,111,103,111,95,99,111,108,111,114,95,49,53,48,120,53,52,100,112,46,112,110,103,41,32,110,111,45,114,101,112,101,97,116,59,109,97,114,103,105,110,45,108,101,102,116,58,45,53,112,120,125,64,109,101,100,105,97,32,111,110,108,121,32,115,99,114,101,101,110,32,97,110,100,32,40,109,105,110,45,114,101,115,111,108,117,116,105,111,110,58,49,57,50,100,112,105,41,123,35,108,111,103,111,123,98,97,99,107,103,114,111,117,110,100,58,117,114,108,40,47,47,119,119,119,46,103,111,111,103,108,101,46,99,111,109,47,105,109,97,103,101,115,47,98,114,97,110,100,105,110,103,47,103,111,111,103,108,101,108,111,103,111,47,50,120,47,103,111,111,103,108,101,108,111,103,111,95,99,111,108,111,114,95,49,53,48,120,53,52,100,112,46,112,110,103,41,32,110,111,45,114,101,112,101,97,116,32,48,37,32,48,37,47,49,48,48,37,32,49,48,48,37,59,45,109,111,122,45,98,111,114,100,101,114,45,105,109,97,103,101,58,117,114,108,40,47,47,119,119,119,46,103,111,111,103,108,101,46,99,111,109,47,105,109,97,103,101,115,47,98,114,97,110,100,105,110,103,47,103,111,111,103,108,101,108,111,103,111,47,50,120,47,103,111,111,103,108,101,108,111,103,111,95,99,111,108,111,114,95,49,53,48,120,53,52,100,112,46,112,110,103,41,32,48,125,125,64,109,101,100,105,97,32,111,110,108,121,32,115,99,114,101,101,110,32,97,110,100,32,40,45,119,101,98,107,105,116,45,109,105,110,45,100,101,118,105,99,101,45,112,105,120,101,108,45,114,97,116,105,111,58,50,41,123,35,108,111,103,111,123,98,97,99,107,103,114,111,117,110,100,58,117,114,108,40,47,47,119,119,119,46,103,111,111,103,108,101,46,99,111,109,47,105,109,97,103,101,115,47,98,114,97,110,100,105,110,103,47,103,111,111,103,108,101,108,111,103,111,47,50,120,47,103,111,111,103,108,101,108,111,103,111,95,99,111,108,111,114,95,49,53,48,120,53,52,100,112,46,112,110,103,41,32,110,111,45,114,101,112,101,97,116,59,45,119,101,98,107,105,116,45,98,97,99,107,103,114,111,117,110,100,45,115,105,122,101,58,49,48,48,37,32,49,48,48,37,125,125,35,108,111,103,111,123,100,105,115,112,108,97,121,58,105,110,108,105,110,101,45,98,108,111,99,107,59,104,101,105,103,104,116,58,53,52,112,120,59,119,105,100,116,104,58,49,53,48,112,120,125,10,32,32,60,47,115,116,121,108,101,62,10,32,32,60,97,32,104,114,101,102,61,47,47,119,119,119,46,103,111,111,103,108,101,46,99,111,109,47,62,60,115,112,97,110,32,105,100,61,108,111,103,111,32,97,114,105,97,45,108,97,98,101,108,61,71,111,111,103,108,101,62,60,47,115,112,97,110,62,60,47,97,62,10,32,32,60,112,62,60,98,62,53,48,50,46,60,47,98,62,32,60,105,110,115,62,84,104,97,116,226,128,153,115,32,97,110,32,101,114,114,111,114,46,60,47,105,110,115,62,10,32,32,60,112,62,84,104,101,32,115,101,114,118,101,114,32,101,110,99,111,117,110,116,101,114,101,100,32,97,32,116,101,109,112,111,114,97,114,121,32,101,114,114,111,114,32,97,110,100,32,99,111,117,108,100,32,110,111,116,32,99,111,109,112,108,101,116,101,32,121,111,117,114,32,114,101,113,117,101,115,116,46,60,112,62,80,108,101,97,115,101,32,116,114,121,32,97,103,97,105,110,32,105,110,32,51,48,32,115,101,99,111,110,100,115,46,32,32,60,105,110,115,62,84,104,97,116,226,128,153,115,32,97,108,108,32,119,101,32,107,110,111,119,46,60,47,105,110,115,62,10]}
  at new StatusCodeError (/Users/justinleewells/pogo/optimizer/node_modules/@request/promise-core/lib/errors.js:32:15)
  at Request.plumbing.callback (/Users/justinleewells/pogo/optimizer/node_modules/@request/promise-core/lib/plumbing.js:95:33)
  at Request.RP$callback [as _callback] (/Users/justinleewells/pogo/optimizer/node_modules/@request/promise-core/lib/plumbing.js:37:31)
  at Request.self.callback (/Users/justinleewells/pogo/optimizer/node_modules/request/request.js:187:22)
  at emitTwo (events.js:87:13)
  at Request.emit (events.js:172:7)
  at Request.<anonymous> (/Users/justinleewells/pogo/optimizer/node_modules/request/request.js:1044:10)
  at emitOne (events.js:77:13)
  at Request.emit (events.js:169:7)
  at IncomingMessage.<anonymous> (/Users/justinleewells/pogo/optimizer/node_modules/request/request.js:965:12)
  at emitNone (events.js:72:20)
  at IncomingMessage.emit (events.js:166:7)
  at endReadableNT (_stream_readable.js:905:12)
  at doNTCallback2 (node.js:450:9)
  at process._tickCallback (node.js:364:17)
```

**Comment by rastapasta** [comment]
The injectMessage got fixed in 607fceae81a8a966ba3f1d9070a64bfe4dce36cf - though be aware that an inject might take some while if the user is not moving (= inject only happens at heartbeat that happens each 30s)

**Comment by rastapasta** [comment]
@prajwalkman thanks for the nice script! If you like, feel free to add it as example.renameAndCleanup.coffee via a pull request, so you appear in the contributer list as well :) otherwise i can add it myself if you wish. Cheers!

**Comment by rastapasta** [comment]
@justinleewells does it work for you by now? otherwise i'm considering closing this issue. Cheers!

**Comment by justinleewells** [comment]
I actually ended up deciding not to use request crafting, so if you were planning on closing it, go for it!
