### ISSUE TITLE
Error "Error: Cannot find module 'http-mite-proxy'"

### ISSUE THREAD

**Issue by greyspy** [rastapasta/pokemon-go-mitm-node#78]
Error: Cannot find module 'http-mitm-proxy'
  at Function.Module._resolveFilename (module.js:325:15)
  at Function.Module._load (module.js:276:25)
  at Module.require (module.js:353:17)
  at require (internal/module.js:12:17)
  at Object.<anonymous> (/Users/Greyston/Desktop/pokemon-go-mitm-node/lib/pokemon-go-mitm.coffee:6:9)
  at Object.<anonymous> (/Users/Greyston/Desktop/pokemon-go-mitm-node/lib/pokemon-go-mitm.coffee:1:1)
  at Module._compile (module.js:409:26)
  at Object.loadFile (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:300:12)
  at Module.require (module.js:353:17)
  at require (internal/module.js:12:17)
  at Object.<anonymous> (/Users/Greyston/Desktop/pokemon-go-mitm-node/example.logTraffic.coffee:9:17)
  at Object.<anonymous> (/Users/Greyston/Desktop/pokemon-go-mitm-node/example.logTraffic.coffee:1:1)
  at Module._compile (module.js:409:26)
  at Object.exports.run (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/coffee-script.js:134:23)
  at compileScript (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:224:29)
  at compilePath (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:174:14)
  at Object.exports.run (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:98:20)
  at Object.<anonymous> (/usr/local/lib/node_modules/coffee-script/bin/coffee:7:41)
  at Module._compile (module.js:409:26)
  at Object.Module._extensions..js (module.js:416:10)
  at Module.load (module.js:343:32)
  at Function.Module._load (module.js:300:12)
  at Function.Module.runMain (module.js:441:10)
  at startup (node.js:139:18)
  at node.js:968:3

Getting this error after running "coffee example.logTraffic.coffee"

Help?

**Comment by trisk** [comment]
Did you forget to `npm install` or maybe `npm install` failed?

**Comment by greyspy** [comment]
@trisk I fixed the issue and i have everything running now all i need to know i how do i run the scripts like get a master ball and stuff?

**Comment by rastapasta** [comment]
please follow the readme and study the examples and their comments - this is a mostly technical project.
