### ISSUE TITLE
Can't get the app to start after configuring MiTM

### ISSUE THREAD

**Issue by ur0** [rastapasta/pokemon-go-mitm-node#8]
Hey everyone, 

I just manged to get this installed on my Linux pc and installed the certs on my phone. However, when I boot PoGo, my app can't get past the loading screen (it's stuck ~20%)

Here are the logs
````
[<-] Request for GetPlayer  {} 

[<-] Request for GetHatchedEggs  {} 

[<-] Request for GetInventory  {} 

[<-] Request for CheckAwardedBadges  {} 

[<-] Request for DownloadSettings  {} 
````

Please help me with this.

**Comment by antfry** [comment]
I can't even past the coffee bit, any ideas?

**Comment by antfry** [comment]
Error: Module did not self-register.
  at Error (native)
  at Object.Module._extensions..node (module.js:434:18)
  at Module.load (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:300:12)
  at Module.require (module.js:353:17)
  at require (internal/module.js:12:17)
  at bindings (/home/test/node_modules/pokemon-go-mitm/node_modules/pokemongo-protobuf/node_modules/node-protobuf/node_modules/bindings/bindings.js:76:44)
  at Object.<anonymous> (/home/test/node_modules/pokemon-go-mitm/node_modules/pokemongo-protobuf/node_modules/node-protobuf/protobuf.js:9:35)
  at Module._compile (module.js:409:26)
  at Object.Module._extensions..js (module.js:416:10)
  at Module.load (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:300:12)
  at Module.require (module.js:353:17)
  at require (internal/module.js:12:17)
  at Object.<anonymous> (/home/test/node_modules/pokemon-go-mitm/node_modules/pokemongo-protobuf/index.js:2:16)
  at Module._compile (module.js:409:26)
  at Object.Module._extensions..js (module.js:416:10)
  at Module.load (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:300:12)
  at Module.require (module.js:353:17)
  at require (internal/module.js:12:17)
  at Object.<anonymous> (/home/test/node_modules/pokemon-go-mitm/lib/pokemon-go-mitm.coffee:7:14)
  at Object.<anonymous> (/home/test/node_modules/pokemon-go-mitm/lib/pokemon-go-mitm.coffee:1:1)
  at Module._compile (module.js:409:26)
  at Object.loadFile (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:300:12)
  at Module.require (module.js:353:17)
  at require (internal/module.js:12:17)
  at Object.<anonymous> (/home/test/node_modules/pokemon-go-mitm/example.logTraffic.coffee:9:17)
  at Object.<anonymous> (/home/test/node_modules/pokemon-go-mitm/example.logTraffic.coffee:1:1)
  at Module._compile (module.js:409:26)
  at Object.exports.run (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/coffee-script.js:134:23)
  at compileScript (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:224:29)
  at compilePath (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:174:14)
  at Object.exports.run (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:98:20)
  at Object.<anonymous> (/usr/local/lib/node_modules/coffee-script/bin/coffee:7:41)
  at Module._compile (module.js:409:26)
  at Object.Module._extensions..js (module.js:416:10)
  at Module.load (module.js:343:32)
  at Function.Module._load (module.js:300:12)
  at Function.Module.runMain (module.js:441:10)
  at startup (node.js:139:18)
  at node.js:968:3

**Comment by ksemeks** [comment]
Quick google search said you have to rebuild your node modules.

npm rebuild 
or
rm -rf node_modules/ && npm install

**Comment by antfry** [comment]
Done, still no luck, same message

**Comment by antfry** [comment]
/home/pokemon-go-mitm-node/node_modules/http-mitm-proxy/lib/middleware/wildcard.js:8
const HOSTNAME_REGEX = /^(.+)(\.[^\.]{4,}(\.[^\.]{1,3})*\.[^\.]+)$/;
^^^^^
SyntaxError: Use of const in strict mode.
  at Module._compile (module.js:439:25)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/home/pokemon-go-mitm-node/node_modules/http-mitm-proxy/lib/proxy.js:24:27)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/home/pokemon-go-mitm-node/node_modules/http-mitm-proxy/index.js:3:18)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/home/pokemon-go-mitm-node/lib/pokemon-go-mitm.coffee:6:9)
  at Object.<anonymous> (/home/pokemon-go-mitm-node/lib/pokemon-go-mitm.coffee:1:1)
  at Module._compile (module.js:456:26)
  at Object.loadFile (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/home/pokemon-go-mitm-node/example.logTraffic.coffee:9:17)
  at Object.<anonymous> (/home/pokemon-go-mitm-node/example.logTraffic.coffee:1:1)
  at Module._compile (module.js:456:26)





sorry, my bad, different error message

**Comment by rastapasta** [comment]
different issues here
@ur0 your setup runs fine, its just sometimes the pokemon servers being trerribly unresponsive. just try again, it will work :)
@antfry weird. but good info: am currently replacing http-mitm-proxy, so your issue might be solved soon :)

**Comment by ur0** [comment]
Thanks @rastapasta.

**Comment by justinleewells** [comment]
@antfry I'm pretty positive that error is from having an outdated version of node.

**Comment by ksemeks** [comment]
@justinleewells @antfry Yes, try updating node to v6

**Comment by antfry** [comment]
Um, tried LTS 4.4.7 and also v6.

**Comment by antfry** [comment]
All fixed. Upgraded npm 3.10.5 and nodejs to 6.3

**Comment by rastapasta** [comment]
:heart:
