### ISSUE TITLE
has no method 'forEach'

### ISSUE THREAD

**Issue by tastypear** [rastapasta/pokemon-go-mitm-node#9]
Ubuntu 14.04.4 LTS
nodejs version v0.10.25
CoffeeScript version 1.10.0
```bash
root@localhost:~/pokemon-go-mitm-node# coffee --nodejs --harmony example.logTraffic.coffee
TypeError: Object #<Set> has no method 'forEach'
  at setToArray (/root/pokemon-go-mitm-node/node_modules/lodash/lodash.js:1133:9)
  at runInContext (/root/pokemon-go-mitm-node/node_modules/lodash/lodash.js:4961:35)
  at Object.<anonymous> (/root/pokemon-go-mitm-node/node_modules/lodash/lodash.js:16376:11)
  at Object.<anonymous> (/root/pokemon-go-mitm-node/node_modules/lodash/lodash.js:16404:3)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/root/pokemon-go-mitm-node/lib/pokemon-go-mitm.coffee:10:5)
  at Object.<anonymous> (/root/pokemon-go-mitm-node/lib/pokemon-go-mitm.coffee:1:1)
  at Module._compile (module.js:456:26)
  at Object.loadFile (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/root/pokemon-go-mitm-node/example.logTraffic.coffee:9:17)
  at Object.<anonymous> (/root/pokemon-go-mitm-node/example.logTraffic.coffee:1:1)
  at Module._compile (module.js:456:26)```

**Comment by tastypear** [comment]
```n stable``` solve the problem.
