### ISSUE TITLE
Error: listen EADDRINUSE :::8081

### ISSUE THREAD

**Issue by architjn** [rastapasta/pokemon-go-mitm-node#94]
Running any of your example gives me this Error

```
[+++] PokemonGo MITM Proxy listening on 8081
[!] Make sure to have the CA cert .http-mitm-proxy/certs/ca.pem installed on your device
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8081
  at Object.exports._errnoException (util.js:1012:11)
  at exports._exceptionWithHostPort (util.js:1035:20)
  at Server._listen2 (net.js:1252:14)
  at listen (net.js:1288:10)
  at Server.listen (net.js:1384:5)
  at /Users/architjn/pokemon-go-mitm-node/node_modules/http-mitm-proxy/lib/proxy.js:86:23
  at /Users/architjn/pokemon-go-mitm-node/node_modules/http-mitm-proxy/lib/ca.js:132:12
  at /Users/architjn/pokemon-go-mitm-node/node_modules/async/lib/async.js:726:13
  at /Users/architjn/pokemon-go-mitm-node/node_modules/async/lib/async.js:52:16
  at /Users/architjn/pokemon-go-mitm-node/node_modules/async/lib/async.js:269:32
  at /Users/architjn/pokemon-go-mitm-node/node_modules/async/lib/async.js:44:16
  at /Users/architjn/pokemon-go-mitm-node/node_modules/async/lib/async.js:723:17
  at /Users/architjn/pokemon-go-mitm-node/node_modules/async/lib/async.js:167:37
  at /Users/architjn/pokemon-go-mitm-node/node_modules/http-mitm-proxy/lib/ca.js:192:12
  at /Users/architjn/pokemon-go-mitm-node/node_modules/async/lib/async.js:52:16
  at /Users/architjn/pokemon-go-mitm-node/node_modules/async/lib/async.js:550:17
  at /Users/architjn/pokemon-go-mitm-node/node_modules/async/lib/async.js:544:17
  at _arrayEach (/Users/architjn/pokemon-go-mitm-node/node_modules/async/lib/async.js:85:13)
  at Immediate.taskComplete (/Users/architjn/pokemon-go-mitm-node/node_modules/async/lib/async.js:543:13)
  at runCallback (timers.js:570:20)
  at tryOnImmediate (timers.js:550:5)
  at processImmediate [as _immediateCallback] (timers.js:529:5)
```

NOTE: This was working before

**Comment by darkoulis12** [comment]
same error here

**Comment by rubenvereecken** [comment]
Kill any and all other instances you have running. If you can't find it, try `pkill node`.

Otherwise, supply a different port. Readme should state how.

**Comment by architjn** [comment]
@rubenvereecken thanks` pkill node` worked
and how do i make my phone to listen to 8081?

i am using android marshmallow

**Comment by rastapasta** [comment]
@architjn  http://www.digitalcitizen.life/how-add-proxy-server-wireless-connection-android
